// <auto-generated />
namespace AutoPartsWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMoneyLimitandSearchLimitfieldsintoIdentityModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMoneyLimitandSearchLimitfieldsintoIdentityModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605091209256_Add MoneyLimit and SearchLimit fields into IdentityModel "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
