// <auto-generated />
namespace AutoPartsWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NameandPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameandPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "201605080828394_Name-and-Phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
