//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Id { get; set; }
        public string ImportId { get; set; }
        public string Brand { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string Supplier { get; set; }
        public string DeliveryTime { get; set; }
    }
}
